=== 279zlj/core/AVSImageStudio3/AVSImageMetaData/trunk/XML/ImageMetaDataExifShema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Описание XML с метаданными типа Exif
  Описание формата Exif см. doc\exifStandard2.pdf
  или в web: http://exif.org/specifications.html
-->
<xs:schema id="ImageMetaDataExif1"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:include schemaLocation="ImageMetaDataCommon.xsd"/>


  <xs:element name="AVSImageMetaDataExif">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="Tag" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>

            <xs:all>

              <xs:element name="ExifTag" minOccurs="1" maxOccurs="1" type="ExifTag"/>
              <xs:element name="CommonTag" minOccurs="0" maxOccurs="1" type="CommonTagType"/>

            </xs:all>

          </xs:complexType>
        </xs:element>

      </xs:sequence>

    </xs:complexType>
  </xs:element>
</xs:schema>

=== 279zlj/core/ASCImageStudio3/AVSImageMetaData/trunk/examples/XML/ImageMetaDataExifExample.xml
<?xml version="1.0" encoding="utf-8"?>
<AVSImageMetaDataExif 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../XML/ImageMetaDataExifShema.xsd"
                      >
  <Tag>
    <ExifTag tagid="270" type="2" count="30">Processed by: Helicon Filter;</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="271" type="2" count="18">NIKON CORPORATION</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="272" type="2" count="10">NIKON D90</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="274" type="3" count="1">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="282" type="5" count="1">300</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="283" type="5" count="1">300</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="296" type="3" count="1">2</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="305" type="2" count="21">Nikon Transfer 1.1 W</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="306" type="2" count="20">2009:04:25 18:40:07</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="531" type="3" count="1">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="34665" type="4" count="1">220</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="33434" type="5" count="1" category="exif">0.0125</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="33437" type="5" count="1" category="exif">4</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="34850" type="3" count="1" category="exif">3</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="36864" type="7" count="4" category="exif">[48,50,50,49]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="36867" type="2" count="20" category="exif">2009:04:25 18:33:17</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="36868" type="2" count="20" category="exif">2009:04:25 18:33:17</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37121" type="7" count="4" category="exif">[1,2,3,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37380" type="10" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37381" type="5" count="1" category="exif">3.2</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37383" type="3" count="1" category="exif">5</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37384" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37385" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37386" type="5" count="1" category="exif">60</ExifTag>
  </Tag>

  <Tag>
    <ExifTag tagid="37510" type="7" count="44" category="exif">[65,83,67,73,73,0,0,0,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37520" type="2" count="3" category="exif">00</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37521" type="2" count="3" category="exif">00</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37522" type="2" count="3" category="exif">00</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="40960" type="7" count="4" category="exif">[48,49,48,48]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="40961" type="3" count="1" category="exif">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="40962" type="3" count="1" category="exif">4288</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="40963" type="3" count="1" category="exif">2848</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="40965" type="4" count="1" category="exif">822</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41495" type="3" count="1" category="exif">2</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41728" type="7" count="1" category="exif">3</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41729" type="7" count="1" category="exif">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41730" type="7" count="8" category="exif">[0,2,0,2,1,2,0,1]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41985" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41986" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41987" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41988" type="5" count="1" category="exif">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41989" type="3" count="1" category="exif">90</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41990" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41991" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41992" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41993" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41994" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="41996" type="3" count="1" category="exif">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="1" type="2" count="4" category="interoperability">R98</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="2" type="7" count="4" category="interoperability">[48,49,48,48]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="259" type="3" count="1" category="thumbnail">6</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="282" type="5" count="1" category="thumbnail">72</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="283" type="5" count="1" category="thumbnail">72</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="296" type="3" count="1" category="thumbnail">2</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="513" type="4" count="1" category="thumbnail">10106</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="514" type="4" count="1" category="thumbnail">10527</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="1" type="7" count="4" category="makernote" categoryid="2">[48,50,49,48]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="4" type="2" count="8" category="makernote" categoryid="2">FINE   </ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="5" type="2" count="13" category="makernote" categoryid="2">AUTO        </ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="7" type="2" count="7" category="makernote" categoryid="2">AF-A  </ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="11" type="8" count="2" category="makernote" categoryid="2">[0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="12" type="5" count="4" category="makernote" categoryid="2">[5.00391,4.00391,0.00390625,0.00390625]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="13" type="7" count="4" category="makernote" categoryid="2">[0,1,6,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="14" type="7" count="4" category="makernote" categoryid="2">[0,1,12,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="17" type="4" count="1" category="makernote" categoryid="2">9050</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="22" type="3" count="4" category="makernote" categoryid="2">[0,0,4288,2848]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="25" type="10" count="1" category="makernote" categoryid="2">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="27" type="3" count="7" category="makernote" categoryid="2">[0,4352,2868,4352,2868,0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="28" type="7" count="4" category="makernote" categoryid="2">[0,1,6,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="29" type="2" count="8" category="makernote" categoryid="2">6148572</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="30" type="3" count="1" category="makernote" categoryid="2">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="31" type="7" count="8" category="makernote" categoryid="2">[48,49,48,48,2,2,0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="34" type="3" count="1" category="makernote" categoryid="2">65535</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="35" type="7" count="58" category="makernote" categoryid="2">[48,49,48,48,83,84,65,78,68,65,82,68,0,0,0,0,0,0,0,0,0,0,0,0,83,84,65,78,68,65,82,68,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-128,-125,-128,-128,-128,-128,-1,-1,-1]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="36" type="7" count="4" category="makernote" categoryid="2">[0,-76,0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="37" type="7" count="14" category="makernote" categoryid="2">[60,1,12,0,2,4,60,1,12,0,2,4,0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="44" type="7" count="94" category="makernote" categoryid="2">[48,49,48,48,5,0,1,100,0,-20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="131" type="1" count="1" category="makernote" categoryid="2">6</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="132" type="5" count="4" category="makernote" categoryid="2">[60,60,2.8,2.8]</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="135" type="1" count="1" category="makernote" categoryid="2">0</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="137" type="1" count="1" category="makernote" categoryid="2">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="138" type="3" count="1" category="makernote" categoryid="2">1</ExifTag>
  </Tag>
  <Tag>
    <ExifTag tagid="139" type="7" count="4" category="makernote" categoryid="2">[84,1,12,0]</ExifTag>
  </Tag>
  <Tag>
